### ISSUE TITLE
[Feature Request] Would you consider adding Null Safety and iOS/iPadOS support?

### ISSUE THREAD

**Issue by AriaShishegaran** [woodemi/quick_usb#12]
@Sunbreak hi there, since you have worked on the desktop release as well as MacOS I wanted to know whether you will continue your work on completing the package to support both null safety and add support for iOS?

**Comment by Sunbreak** [comment]
Null-Safety is coming. But I don't think I'll take into iOS/iPadOS because of https://mfi.apple.com/

**Comment by digitalkirkley** [comment]
Would you be able to update the Ffi to 1.0.0 please? I was going to test this on latest Flutter Linux desktop but has an error for the getter 'addressOf' isn't defined for the class Utf8.  Thank you.

**Comment by Sunbreak** [comment]
> Would you be able to update the Ffi to 1.0.0 please? I was going to test this on latest Flutter Linux desktop but has an error for the getter 'addressOf' isn't defined for the class Utf8. Thank you.

Could you post another issue for null-safety?

**Comment by Sunbreak** [comment]
> Would you be able to update the Ffi to 1.0.0 please? I was going to test this on latest Flutter Linux desktop but has an error for the getter 'addressOf' isn't defined for the class Utf8. Thank you.

Could you try https://github.com/woodemi/quick_usb/pull/13?

**Comment by digitalkirkley** [comment]
Yes sure - will give this a go; brilliant thank you.

**Comment by Sunbreak** [comment]
Could you try #17 ?

**Comment by Sunbreak** [comment]
Closed for null-safety is supported. File iOS support for another issue please
