### ISSUE TITLE
how to get device details 

### ISSUE THREAD

**Issue by mjafartp** [woodemi/quick_usb#21]
how to get details product name, manufacture and other details

**Comment by Sunbreak** [comment]
USB protocol is complicated. Some devices have those properties set but other don't

Try with https://github.com/woodemi/libusb.dart/tree/master/example

**Comment by shaxxx** [comment]
Should be closed with https://github.com/woodemi/quick_usb/pull/30

**Comment by Sunbreak** [comment]
> Should be closed with #30

Thanks for the remind :)
