### ISSUE TITLE
How to properly read data with this library?

### ISSUE THREAD

**Issue by MateoSegura** [woodemi/quick_usb#25]
Hello,

I am trying to use this library with an Arduino to create a simple data logger. The problem is that the Arduino constantly outputs data & I need update a list on my flutter program with such data. How can I implement something like this with the bulk transfer method? I do not understand what the end point is, it says that device has endpoint '1'. Any ideas or suggestions are greatly appreciated.

<img width="829" alt="Screen Shot 2021-07-06 at 1 06 03 PM" src="https://user-images.githubusercontent.com/70351278/124640429-643c5d80-de5b-11eb-99d3-5ce83333c8af.png">

**Comment by Sunbreak** [comment]
Sorry. The lib is mostly a wrapper of libusb: https://github.com/libusb/libusb on Flutter PC. You'd better learn for libusb

**Comment by Sunbreak** [comment]
Sorry. The lib is mostly a wrapper of libusb: https://github.com/libusb/libusb on Flutter PC. You'd better learn for libusb

**Comment by Sunbreak** [comment]
Sorry. The lib is mostly a wrapper of libusb: https://github.com/libusb/libusb on Flutter PC. You'd better learn for libusb

**Comment by MateoSegura** [comment]
Ok, thank you!. I'll look into it
