### ISSUE TITLE
Define a timeout parameter

### ISSUE THREAD

**Issue by fanchou** [woodemi/quick_usb#34]
https://github.com/woodemi/quick_usb/blob/1f295896694f56f895297d44c90d447beb7b4e40/android/src/main/kotlin/com/example/quick_usb/QuickUsbPlugin.kt#L153

Maybe we can define a timeout parameter.  Sometimes the default timeout may not be finished. When I print,  only print half of the content, especially when there are pictures.

**Comment by Sunbreak** [comment]
Yep. I'm a little busy right now. Could you file a PR?
