### ISSUE TITLE
on macos Big Sur: claimInterface always return false

### ISSUE THREAD

**Issue by vtongcoder** [woodemi/quick_usb#37]
I try the example of this package on macOs Big Sur 11.6.
I open a device: ok
getConfig: ok
claimInterface false

I don't know why.
Do I need to config something in order the quick_usb work o macOS?
thanks

**Comment by vtongcoder** [comment]
> Nope. Mine is Big Sur and it works fine. There is other config to check I think

I'm still working to figure out what cause the problem.

**Comment by Sunbreak** [comment]
You could check Web-USB in Chrome: https://web.dev/usb/

**Comment by Sunbreak** [comment]
You'd better try https://github.com/woodemi/web_usb.dart to ensure your operation permission
