### ISSUE TITLE
printing PDF

### ISSUE THREAD

**Issue by selvam920** [woodemi/quick_usb#41]
can we use this plugin transfer pdf byte array to attched usb printer

**Comment by Sunbreak** [comment]
Theoretically YES. But I didn't try yet

**Comment by selvam920** [comment]
ok, i will try and let you know

**Comment by Sunbreak** [comment]
I'd like to close it if no further info

**Comment by selvam920** [comment]
Im not able to try, can you share sample to to print pdf?

**Comment by Sunbreak** [comment]
Sorry I have no idea how your printer works. Different printer has different protocol.

**Comment by selvam920** [comment]
General printer luke ho or epson
