### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by bikram0000** [woodemi/quick_usb#54]
I can get the device list but am not able to open the device, always return false
![Screenshot 2022-03-09 113222](https://user-images.githubusercontent.com/43512518/157381966-73e10b21-074f-488e-98ce-62724a3639ba.jpg)
![Screenshot 2022-03-09 113240](https://user-images.githubusercontent.com/43512518/157381977-4446a75a-4a7d-42ba-b6cb-8cf13faa3ab3.jpg)
.

**Comment by Sunbreak** [comment]
Could you try https://github.com/woodemi/libusb.dart?

How is the open result?

**Comment by bikram0000** [comment]
F:\ANDROID\Git Project Plugin\libusb.dart>pub run ffigen
"The top level `pub.bat` command is deprecated. Use `dart pub` instead."
Running in Directory: 'F:\ANDROID\Git Project Plugin\libusb.dart'
Input Headers: [libusb-1.0\libusb.h]
[WARNING]: Skipped Function 'libusb_cpu_to_le16', inline functions are not supported.
[WARNING]: Removed All Struct Members from libusb_bos_dev_capability_descriptor(libusb_bos_dev_capability_descriptor), Flexible array members not s
upported.
[WARNING]: Removed All Struct Members from libusb_bos_descriptor(libusb_bos_descriptor), Flexible array members not supported.
[WARNING]: Removed All Struct Members from libusb_transfer(libusb_transfer), Flexible array members not supported.
[WARNING]: Skipped Function 'libusb_control_transfer_get_data', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_control_transfer_get_setup', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_fill_control_setup', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_fill_control_transfer', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_fill_bulk_transfer', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_fill_bulk_stream_transfer', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_fill_interrupt_transfer', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_fill_iso_transfer', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_set_iso_packet_lengths', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_get_iso_packet_buffer', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_get_iso_packet_buffer_simple', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_get_descriptor', inline functions are not supported.
[WARNING]: Skipped Function 'libusb_get_string_descriptor', inline functions are not supported.
Finished, Bindings generated in F:\ANDROID\Git Project Plugin\libusb.dart\lib\src\libusb.ffigen.dart

**Comment by Sunbreak** [comment]
Could you try something like `pub run example/listdevs.dart`, not `ffigen`

You could change the code inside `listdevs.dart` to open the device you list

**Comment by bikram0000** [comment]
Building package executable...
Built libusb:listDeviceProducts.
1165:49408 open error: LIBUSB_ERROR_NO_DEVICE
1226:28784 open error: LIBUSB_ERROR_NOT_FOUND
4070:33054 open error: LIBUSB_ERROR_NOT_SUPPORTED
32902:41837 iProduct empty
32903:2730 iProduct empty
deviceProductInfo [MapEntry(1165:49408: ), MapEntry(1226:28784: ), MapEntry(4070:33054: ), MapEntry(32902:41837: ), MapEntry(32903:2730: )]

4070 is a thermal printer and it perfectly working with macOS but not open in windows

**Comment by Sunbreak** [comment]
`LIBUSB_ERROR_NOT_SUPPORTED` seems you haven't installed the right driver

**Comment by bikram0000** [comment]
right driver for the printer? i think I have installed the correct driver and it's working with test software.

**Comment by bikram0000** [comment]
thank you for your help I installed zadig and reinstall the driver, my problem is solved now.

**Comment by Sunbreak** [comment]
> I also have the same problem. I ran listdevs.dart. It lists the devices. But still openDevice returns false.

What about `listDeviceProducts.dart` beside `listdevs.dart`?

**Comment by kalimero-plt** [comment]
Thank you for your reply. I tried what you said. It gave the error LIBUSB_ERROR_NOT_SUPPORTED. I installed Zadig and reinstall the driver. OpenDevice returned true. Problem solved.
