### ISSUE TITLE
quick_usb demo can get device list ,but my project get device list empty on macos

### ISSUE THREAD

**Issue by ludy520** [woodemi/quick_usb#57]

**Comment by Sunbreak** [comment]
Could you try `example/listdevs.dart` inside https://github.com/woodemi/libusb.dart?

```sh
% git clone https://github.com/woodemi/libusb.dart?
% cd libusb.dart
% flutter pub get
% flutter pub run example/listdevs.dart
```

**Comment by ludy520** [comment]
example/listdevs.dart 可以获取到，quick_usb的demo也是可以获取到deviceList，然后import到自己的项目，获取到的列表就是空的
<img width="516" alt="image" src="https://user-images.githubusercontent.com/4113005/162550763-6073d276-b12b-4a30-8bbf-2a5389df7ee8.png">

**Comment by Sunbreak** [comment]
You need [com.apple.security.device.usb](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_usb) in your entitlement file (Debug & Release) according to https://developer.apple.com/documentation/security/app_sandbox

```xml
	<key>com.apple.security.device.usb</key>
	<true/>
```

https://github.com/woodemi/quick_usb/blob/e07a13aa907a73e9a1e934c2671a542f650e1501/example/macos/Runner/DebugProfile.entitlements#L9-L10

https://github.com/woodemi/quick_usb/blob/e07a13aa907a73e9a1e934c2671a542f650e1501/example/macos/Runner/Release.entitlements#L7-L8

**Comment by Sunbreak** [comment]
进Flutter Desktop群聊，加微信：wk2311007
